### ISSUE TITLE
Add dimension information to "Collection"

### ISSUE THREAD

**Issue by flahn** [Open-EO/openeo-r-backend#12]
For the test implementation on UDFs we need information on collections that specifies the dimensionality for passing data to an UDF and reading the data from an UDF back into the system.

Also each offered process in this back-end need to modify this dimensionality aspect, when they modify the collection. 

Notes: collections are the backbone for the data storage in the r back-end and currently it is assumed that the data has always all dimensions (space, time, bands).

**Comment by pramitghosh** [comment]
Some points regarding some ideas and suggestions:

- I believe the current implementation have functions to modify (add/subtract) dimensions of a Collection object with modifier functions when objects of the Process class act on it. While this is fine for sequential processing, please also consider having the dimensionality as vector too with integer values (even if side-by-side with the current implementation). Collection objects having 0 and 1 as possible values while Process objects having -1, 0 and 1 as possible values for dropping/keeping it unchanged/adding dimensionalities. One advantage of this would be that the dimensionality of the resultant object after starting from an initial dimensionality and an ordered set of processes by simply adding the associated vectors up. This could be useful to find the dimensionality of any intermediate Collection object at a later stage (e.g. some sort of a traceback) by just looking at these vectors which could be stored in a log.

- For the UDFs, the dimensionality of the incoming object has to be provided in a generic format (e.g. CSV) possibly with the legend file itself for typechecking the UDF output.

- There has to be an agreement between the order used to represent the different dimensions with the UDF implementation - i.e. which index represent which dimension.

- In order to keep it it simpler for the users the lesser number of dimensions being used better it is. For example, mutually exclusive dimensions such as "whether raster or feature?" can be merged into a single value instead of needing two indices for it. So, one could have 1 representing raster, 0 representing vector and `NA` representing neither of them (e.g. a time-series of values).

- We can also develop some simple checking functions of the dimensionalities themselves - e.g. a raster having no space dimensions is meaningless and so on. But this will probably not be necessary or required, but can be kept in mind in case such requirements emerge later in the future.
