### ISSUE TITLE
Calling a synchronous task will not yield an image

### ISSUE THREAD

**Issue by flahn** [Open-EO/openeo-r-backend#4]
Connect the download function with the "/api/jobs/evaluate=sync" operation

**Comment by GreatEmerald** [comment]
Related to that, if the result is supposed to be a `Raster*` object, then the package should also require and load the `raster` package. It doesn't seem to be doing that yet.

**Comment by GreatEmerald** [comment]
When do you expect to implement this? I'm giving a presentation on the current state of openEO to WUR tomorrow, so I'm wondering if I should stick with the current output I have in Jupyter notebook, or wait for a fix to this. It would be pretty sweet to have an actual image.

**Comment by flahn** [comment]
I think i can come up with a fix until tomorrow. If I don't manage to do it, then I will notify you.

**Comment by flahn** [comment]
Created an issue for the raster package integration: Open-EO/openeo-r-client#9

**Comment by GreatEmerald** [comment]
Great, thanks!

**Comment by flahn** [comment]
fix this for Open-EO/openeo-r-backend#3

**Comment by GreatEmerald** [comment]
It works, thanks!

The only problem is that the result of `executeTask()` is still `raw`, so that cannot to coerced into a `RasterLayer`. It works with a workaround of:
```R
writeBin(Result, "output.tif")
Result = raster("output.tif")
```
...which is a bit roundabout. I'm not sure if there's a way to coerce the file (which has metadata etc.) into a `RasterLayer` without going through a file intermediary. Either way there should be at least an option to choose a file to store the data in, since the result can be quite large and not fit into the memory easily.

**Comment by GreatEmerald** [comment]
Ah, I had missed your email, I see the `output` argument now. Thanks!
