### ISSUE TITLE
Move large data files out of the repository

### ISSUE THREAD

**Issue by GreatEmerald** [Open-EO/openeo-r-backend#8]
The `openeo.server$loadDemo()` function should download and load the demo files, instead of having the files be always downloaded over again on each update of the backend. The sooner this is done, the better, since it's an invasive procedure that involves rewriting the whole history of the repository, which will cause issues on forks (if any). It would also save quite a bit of time every time users update the backend package.

**Comment by flahn** [comment]
I pushed those changes into the develop branch. Maybe you can also verify if it is working as intended. Then I will push the changes also to master.

**Comment by GreatEmerald** [comment]
Sure, we'll try that to make sure it works with the new changes to the function.

Note, however, that this is not enough: you have to rewrite the history of the Git repository, because it stores all files forever otherwise. See https://help.github.com/articles/removing-sensitive-data-from-a-repository/.

**Comment by flahn** [comment]
You are probably right that the data should be removed from all commits. But this would mean that the older version, e.g. all 0.1.x versions won't work anymore, since they depend on the data to be in the package. However, we are using tags and releases that provide the current status of the package at that point. I don't know if those releases are also affected from the removal process. If not, then we have at least working releases that we could use.

**Comment by m-mohr** [comment]
I tried this out and the download process is not working for me.
On Windows 10 I get:
>  Error in download.file(url = "https://uni-muenster.sciebo.de/s/aiAEcP6DtHQ7t2Q/download",  : 
  cannot open destfile 'C:/Users/m_mohr08/Documents/R/win-library/3.4/openEO.R.Backend/extdata/openeo-demo.zip', reason 'No such file or directory' 

It seems the reason is that the extdata directory in openEO.R.Backend doesn't exist. After creating the directory manually it works. So the directory should be created by R before trying to download the file to this directory.

**Comment by flahn** [comment]
OK, I will look into it. On a first glimbse, it seems that I just need to create directories recursively.

**Comment by m-mohr** [comment]
Yeah, it's working as suggested in PR #10 :)
